config/routes.rb
Rails.application.routes.draw do
  root "entries#index"
  resources :entries

end

app/models/entry.rb
class Entry < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :all_entries, only: [:index,                   :create, :update, :destroy]
  before_action :set_entry,   only: [        :show,     :edit,          :update, :destroy]

  respond_to :html, :js

  def index
  end

  def show
  end

  def new
    @entry = Entry.new
  end

  def edit

    #$("[id*=#entry-]") ->
    #  $(this).html("<%= j(render partial: 'entries/entry', :locals => { entry: @entry) } %>")
    #$("#entries").html("<%= j(render partial: 'entries/entry', collection: @entries, as: :entry) %>")
    
  end

  def create
    @entry = Entry.create(entry_params)
  end

  def update
    @entry.update(entry_params)
  end

  def destroy
    @entry.destroy
  end

  private

    def all_entries
      @entries = Entry.all
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def entry_params
      params.require(:entry).permit(:body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/_entry.html.haml
/ index.html.haml - entries
/  = render "entires/entry", collection: @entries, as: :entry
%li{ id: "entry-#{entry.id}" }

  = entry.body

  = link_to edit_entry_path(entry), remote: true do
    %button "Edit"

  = link_to entry, method: :delete, data: { confirm: "Delete?" }, remote: true do
    %button "Delete"

app/views/entries/_form.html.haml
= simple_form_for @entry, remote: true do |f|
  = f.input :body
  = f.button :submit, :disable_with => "Submitting…"

app/views/entries/index.html.haml
%h1 Listing entries

= link_to new_entry_path, remote: true do
  New

#entry-form{ display: "none" }

%ul#entries
  = render partial: 'entries/entry', collection: @entries, as: :entry

app/views/entries/show.html.haml
%p#notice= notice
%p
  %strong Body:
  = @entry.body
= link_to 'Edit', edit_entry_path(@entry)
|
= link_to 'Back', entries_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ajaxdemo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>